# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
    paths:
      - "package.json"

env:
  GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  windows:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@v2

      - run: |
          git config --global user.name SurajRathod 
          git config --global user.email surajrathod999@gmail.com

      - name: Setup Node.js
        uses: actions/setup-node@v1.4.2
        with:
          node-version: ${{matrix.node_version}}

      - name: install package
        run: npm install

      - name: make platform file
        run: npm run make

      - name: release to Github
        run: npm run release
