# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node_version: ['12']
        os: [ubuntu-latest, windows-latest]
    steps:
     - uses: actions/checkout@v2

     - name: Setup Node.js
       uses: actions/setup-node@v1.4.2
       with:
         node-version: ${{matrix.node_version}}
    
     - name: install package
       run: npm install
       
     - name: make platform file
       run: npm run make
       
     - uses: actions/upload-artifact@v2
       with:
        name: ${{matrix.os}}
        path: out/make

